### ISSUE TITLE
Air Mobile I and Air Mobile II have the same unique

### ISSUE THREAD

**Issue by marek22k** [Mechworks-all-day/Extra-Promotions#6]
Air Mobile I and Air Mobile II have the same unique.
https://github.com/Mechworks-all-day/Extra-Promotions/blob/main/jsons/UnitPromotions.json#L77
https://github.com/Mechworks-all-day/Extra-Promotions/blob/main/jsons/UnitPromotions.json#L83

**Comment by Mechworks-all-day** [comment]
> Air Mobile I and Air Mobile II have the same unique. https://github.com/Mechworks-all-day/Extra-Promotions/blob/main/jsons/UnitPromotions.json#L77 https://github.com/Mechworks-all-day/Extra-Promotions/blob/main/jsons/UnitPromotions.json#L83

That's deliberate; they use a + on the range.
So AM 2 *adds* to the range of AM 1.
